[toolchain]
anchor_version = "0.28.0-6cf200493a307c01487c7b492b4893e0d6f6cb23"

[features]
resolution = true
skip-lint = false

[programs.localnet]
level_manager = "8ruAJmkjRC32HeWrHo7ng7kWmirHKiW7Djrafs5EgtVM"

[programs.devnet]
level_manager = "8ruAJmkjRC32HeWrHo7ng7kWmirHKiW7Djrafs5EgtVM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
idl-publish = "anchor idl init -f target/idl/level_manager.json 8ruAJmkjRC32HeWrHo7ng7kWmirHKiW7Djrafs5EgtVM"
idl-upgrade = "anchor idl upgrade 8ruAJmkjRC32HeWrHo7ng7kWmirHKiW7Djrafs5EgtVM -f target/idl/level_manager.json"